# This workflow will build a Java project with Maven
# For more information see: https://help.github.com/actions/language-and-framework-guides/building-and-testing-java-with-maven

name: build
on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:

    runs-on: ubuntu-latest

    strategy:
      matrix:
        java-version: [8, 11, 17]

    steps:
    - uses: actions/checkout@v2
    - name: Set up JDK ${{ matrix.java-version }}
      uses: actions/setup-java@v1
      with:
        java-version: ${{ matrix.java-version }}
    - name: Build with Maven
      run: ./mvnw clean install -Pci-install -B -U -e && bash ./.middleware-common/check_format.sh
    - name: Test with Maven
      run: ./mvnw package -Pci-test
    - name: Codecov
      uses: codecov/codecov-action@v1

